manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pim447
      url-base: https://github.com/t0bybr
   
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    - name: pim447
      remote: pim447
      revision: main  
  self:
    path: config
