manifest:
  defaults:
     revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mwandzik
      url-base: https://github.com/mwandzik
   
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # zmk-driver-pim447
    - name: zmk-driver-pim447
      remote: mwandzik
      revision: master
  self:
    path: config
