manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-driver-pim447
      url-base: https://github.com/mwandzik
   
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # trackball
    - name: mwandzik
      remote: zmk-driver-pim447
      revision: main
  self:
    path: config
